Add missing libxslt for Debian to bootstrap cinder
Fixes:

Collecting lxml<=3.3.3,>=2.3 (from cinder==2014.2.3.dev13)
  Downloading lxml-3.3.3.tar.gz (3.5MB)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Building lxml version 3.3.3.
    Building without Cython.
    ERROR: /bin/sh: 1: xslt-config: not found
    ** make sure the development packages of libxml2 and libxslt are installed **
    Using build configuration of libxslt